Length feat
kmlv/RiskAttitudesSocialPreferences pull request #1
Opened 2021-12-20 20:57 UTC by Sergio2405

<strong>1. Aleatorizar nro de tareas por bloque</strong>

- Cree un loop que iterara por cada bloque para que luego tomara un numero aleatorio de tareas que iba cambiando dependiendo de cuantas tareas habian en el bloque.

<strong>2. Aleatorizar orden de las tareas

- Dentro de la funcion shuffle en en el config.py se introdujo una linea que aleatorizaba el orden de las tareas.

<strong>3. 10/12/15 tareas

- Para cada bloque se pueden tener 10 /12 / 15 tareas. No es necesario que todos los bloques tengan el mismo numero de tareas

2021-12-21 14:58 UTC, Sergio2405 commented
@mgutierrezc acabo de hacer un commit sobre lo de 10/12/15 tareas

2022-01-21 23:39 UTC, Sergio2405 commented
@mgutierrezc Marco ya había este pull request de mi branch así que esta listo con los últimos commits: 

Este pull request tiene la traducción de la app demograp que es en donde hay preguntas demográficas y preguntas cognitivas. 
<ul>
      <li> Esta fue creada con ugettext_lazy de django.utils.transalation </li>
      <li> Tambien se aplico {% blocktrans %} a oraciones en los templates </li>
      <li> Se creo una carpeta locale que tiene un file django.po y django.mo que permiten hacer la traducción </li>
</ul>

2022-01-25 04:35 UTC, mgutierrezc requested changes
@Sergio2405 chequea los conflictos con el main

2022-01-25 18:08 UTC, Sergio2405 commented
@mgutierrezc ya marco ya solucione los conflictos e hice un testeo y todo bien.

2022-01-26 02:56 UTC, mgutierrezc requested changes
@Sergio2405 problemas al inicio
![image](https://user-images.githubusercontent.com/43623521/151096442-c9b645b0-1668-461d-9668-3a92a5230f5f.png)

2022-01-26 02:56 UTC, mgutierrezc commented
> @Sergio2405 problemas al inicio ![image](https://user-images.githubusercontent.com/43623521/151096442-c9b645b0-1668-461d-9668-3a92a5230f5f.png)

![image](https://user-images.githubusercontent.com/43623521/151096492-ccf94adc-be5b-4d48-ab77-eb6485e20940.png)

2022-01-26 15:31 UTC, mgutierrezc requested changes
@Sergio2405, realicemos las ediciones al README en inglés pls

2022-01-26 16:33 UTC, Sergio2405 commented
@mgutierrezc ya marco ya esta en ingles

2022-01-26 16:58 UTC, mgutierrezc approved these changes

2022-01-26 16:58 UTC, merged